name: Catalysm
favicon: null
layout_spectrum: 0.2801
typography_spectrum: 0.2629412056412548
title: Catalysm Practice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8161544180475175
  lightness: 0.2000505616888404
  saturation: 0.994872419629246
  rhythmicContrast: 0.34095151466317475
purpose: []
