name: Catalysm
favicon: null
layout_spectrum: 0.2801
typography_spectrum: 0.63022
title: Catalysm Practice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#97bee3'
    - '#13171a'
    - '#00864e'
    - '#857567'
  brandStrength: 0.8161544180475175
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
